CREATE TABLE `sys_history` (
  `hist_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `hist_ts` timestamp NULL DEFAULT NULL,
  `hist_method` varchar(1) DEFAULT NULL,
  `hist_object_name` varchar(80) DEFAULT NULL,
  `hist_object_id` bigint(20) unsigned DEFAULT NULL,
  `hist_object` longtext DEFAULT NULL,
  PRIMARY KEY (`hist_id`)
);
CREATE TABLE `sys_lang` (
  `lang_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `lang_name` varchar(32) NOT NULL DEFAULT '',
  `lang_code` varchar(3) DEFAULT NULL,
  `lang_iso` varchar(10) DEFAULT NULL,
  `lang_flag` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`lang_id`),
  UNIQUE KEY `ix_lang_lang_name` (`lang_name`)
);
CREATE TABLE `sys_country` (
  `cnty_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `cnty_name` varchar(80) NOT NULL DEFAULT '',
  `cnty_code` varchar(3) DEFAULT '',
  PRIMARY KEY (`cnty_id`),
  UNIQUE KEY `ix_country_cnty_name` (`cnty_name`)
);
CREATE TABLE `sys_email` (
  `email_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `lang_id` bigint(20) unsigned NOT NULL,
  `email_code` varchar(80) NOT NULL DEFAULT '',
  `email_subject` varchar(255) DEFAULT NULL,
  `email_body` longtext DEFAULT NULL,
  `email_from` varchar(255) DEFAULT NULL,
  `email_from_name` varchar(255) DEFAULT NULL,
  `email_reply_to` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`email_id`),
  KEY `fk_email_broker` (`brk_id`),
  KEY `fk_email_lang` (`lang_id`),
  CONSTRAINT `fk_email_lang` FOREIGN KEY (`lang_id`) REFERENCES `sys_lang` (`lang_id`)
);
CREATE TABLE `sys_jobqueue` (
  `jobq_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `jobq_name` varchar(255) DEFAULT NULL,
  `jobq_desc` longtext DEFAULT NULL,
  `grp_id` bigint(20) unsigned DEFAULT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  `jobq_type` enum('LOOP','ONCE') NOT NULL DEFAULT 'ONCE',
  `jobq_status` enum('WAITING','FINISHED','ERROR','PENDING','RETRY') NOT NULL DEFAULT 'WAITING',
  `jobq_ts` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `jobq_last_report` longtext DEFAULT NULL,
  `jobq_last_ts` timestamp NULL DEFAULT NULL,
  `jobq_service` varchar(80) DEFAULT NULL,
  `jobq_method` varchar(80) DEFAULT NULL,
  `jobq_params` longtext DEFAULT NULL,
  `jobq_max_retry` int(4) NOT NULL DEFAULT 1,
  `jobq_nb_retry` int(4) DEFAULT NULL,
  `jobq_next_minutes` bigint(20) DEFAULT NULL,
  `jobq_next_retry` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`jobq_id`),
  KEY `fk_jobqueue_broker` (`brk_id`),
  KEY `fk_jobqueue_group` (`grp_id`),
  KEY `fk_jobqueue_user` (`user_id`)
);
CREATE TABLE `sys_jobqueue_histo` (
  `jobqh_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `jobq_id` bigint(20) unsigned NOT NULL,
  `brk_id` bigint(20) unsigned NOT NULL,
  `jobqh_ts` timestamp NULL DEFAULT NULL,
  `jobqh_msg` longtext DEFAULT NULL,
  `jobqh_status` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`jobqh_id`),
  KEY `fk_jobqueue_histo_jobqueue` (`jobq_id`),
  KEY `fk_jobqueue_histo_broker` (`brk_id`),
  CONSTRAINT `fk_jobqueue_histo_jobqueue` FOREIGN KEY (`jobq_id`) REFERENCES `sys_jobqueue` (`jobq_id`)
);
CREATE TABLE `sys_message` (
  `msg_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `msg_object_name` varchar(80) DEFAULT NULL,
  `msg_object_id` bigint(20) unsigned DEFAULT NULL,
  `lang_id` bigint(20) unsigned DEFAULT NULL,
  `msg_ts` timestamp NULL DEFAULT NULL,
  `msg_status` enum('WAITING','PENDING','OK','ERROR') NOT NULL DEFAULT 'WAITING',
  `msg_type` enum('EMAIL','SMS') NOT NULL DEFAULT 'EMAIL',
  `msg_dest` text DEFAULT NULL,
  `msg_cc` text DEFAULT NULL,
  `msg_bcc` text DEFAULT NULL,
  `msg_subject` text DEFAULT NULL,
  `msg_body` longtext DEFAULT NULL,
  `msg_pj1` varchar(255) DEFAULT NULL,
  `msg_pj2` varchar(255) DEFAULT NULL,
  `msg_pj3` varchar(255) DEFAULT NULL,
  `msg_pj4` varchar(255) DEFAULT NULL,
  `msg_send_ts` timestamp NULL DEFAULT NULL,
  `msg_send_error` text DEFAULT NULL,
  `msg_from` text DEFAULT NULL,
  `msg_reply_to` text DEFAULT NULL,
  PRIMARY KEY (`msg_id`),
  KEY `fk_message_lang` (`lang_id`),
  KEY `fk_message_broker` (`brk_id`),
  CONSTRAINT `fk_message_lang` FOREIGN KEY (`lang_id`) REFERENCES `sys_lang` (`lang_id`)
);
CREATE TABLE `sys_notification` (
  `notif_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `notif_text` longtext DEFAULT NULL,
  `notif_subject` varchar(80) DEFAULT NULL,
  `notif_object_name` varchar(80) DEFAULT NULL,
  `notif_object_id` bigint(20) DEFAULT NULL,
  `notif_code` varchar(80) DEFAULT NULL,
  `notif_ts` timestamp NULL DEFAULT NULL,
  `notif_type` enum('ERROR','WARNING','INFORMATION','MANUAL','OTHER') NOT NULL DEFAULT 'OTHER',
  `notif_read` int(1) NOT NULL DEFAULT 0,
  `notif_read_ts` timestamp NULL DEFAULT NULL,
  `user_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`notif_id`),
  KEY `fk_notification_broker` (`brk_id`),
  KEY `fk_notification_user` (`user_id`)
);
CREATE TABLE `sys_rate` (
  `rate_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `rate_money_from` varchar(3) DEFAULT NULL,
  `rate_money_to` varchar(3) DEFAULT NULL,
  `rate_ts` timestamp NULL DEFAULT NULL,
  `rate_change` decimal(16,9) DEFAULT NULL,
  PRIMARY KEY (`rate_id`)
);
INSERT INTO `sys_lang` (`lang_id`, `lang_name`, `lang_code`, `lang_iso`, `lang_flag`)
VALUES
    (365, 'Non défini', NULL, NULL, NULL),
    (366, 'Anglais', 'en', 'en-GB', 'gbr'),
    (367, 'Espagnol', 'es', 'es-ES', 'esp'),
    (368, 'Français', 'fr', 'fr-FR', 'fra');
INSERT INTO `sys_country` (`cnty_id`, `cnty_name`, `cnty_code`)
VALUES
    (25534, 'Afghanistan', NULL),
    (25535, 'Afrique du sud', NULL),
    (25536, 'Albanie', NULL),
    (25537, 'Algérie', NULL),
    (25538, 'Allemagne', NULL),
    (25539, 'Angola', NULL),
    (25540, 'Anguilla', NULL),
    (25541, 'Antigua et barbuda', NULL),
    (25542, 'Antilles néerlandaises', NULL),
    (25543, 'Arabie saoudite', NULL),
    (25544, 'Argentine', NULL),
    (25545, 'Arménie', NULL),
    (25546, 'Aruba', NULL),
    (25547, 'Australie', NULL),
    (25548, 'Autriche', NULL),
    (25549, 'Azerbaïdjan', NULL),
    (25550, 'Bahamas', NULL),
    (25551, 'Bahreïn', NULL),
    (25552, 'Bangladesh', NULL),
    (25553, 'Barbade', NULL),
    (25554, 'Bélarus', NULL),
    (25555, 'Belau', NULL),
    (25556, 'Belgique', NULL),
    (25557, 'Belize', NULL),
    (25558, 'Bénin', NULL),
    (25559, 'Bermudes', NULL),
    (25560, 'Bhoutan', NULL),
    (25561, 'Biélorussie', NULL),
    (25562, 'Birmanie - myanmar', NULL),
    (25563, 'Bolivie', NULL),
    (25564, 'Bosnie herzégovine', NULL),
    (25565, 'Botswana', NULL),
    (25566, 'Brésil', NULL),
    (25567, 'Bruneï', NULL),
    (25568, 'Bulgarie', NULL),
    (25569, 'Burkina faso', NULL),
    (25570, 'Burundi', NULL),
    (25571, 'Cambodge', NULL),
    (25572, 'Cameroun', NULL),
    (25573, 'Canada', NULL),
    (25574, 'Canaries', NULL),
    (25575, 'Cap vert', NULL),
    (25576, 'Centrafrique', NULL),
    (25577, 'Chili', NULL),
    (25578, 'Chine', NULL),
    (25579, 'Chypre', NULL),
    (25580, 'Colombie', NULL),
    (25581, 'Comores', NULL),
    (25582, 'Congo (rép. démocratique)', NULL),
    (25583, 'Congo brazzaville', NULL),
    (25584, 'Corée du nord', NULL),
    (25585, 'Corée du sud', NULL),
    (25586, 'Costa rica', NULL),
    (25587, 'Cote d\'ivoire', NULL),
    (25588, 'Croatie', NULL),
    (25589, 'Cuba', NULL),
    (25590, 'Danemark', NULL),
    (25591, 'Djibouti', NULL),
    (25592, 'Dominique', NULL),
    (25593, 'Egypte', NULL),
    (25594, 'Eire', NULL),
    (25595, 'Emirats arabes unis', NULL),
    (25596, 'Equateur', NULL),
    (25597, 'Erythrée', NULL),
    (25598, 'Espagne', NULL),
    (25599, 'Estonie', NULL),
    (25600, 'Andorre', NULL),
    (25601, 'Etats unis', NULL),
    (25602, 'Ethiopie', NULL),
    (25603, 'Fidji', NULL),
    (25604, 'Finlande', NULL),
    (25605, 'France', NULL),
    (25606, 'Gabon', NULL),
    (25607, 'Gambie', NULL),
    (25608, 'Géorgie', NULL),
    (25609, 'Ghana', NULL),
    (25610, 'Grèce', NULL),
    (25611, 'Grenade', NULL),
    (25612, 'Guadeloupe', NULL),
    (25613, 'Guatemala', NULL),
    (25614, 'Guinée', NULL),
    (25615, 'Guinée-bissau', NULL),
    (25616, 'Guinée-equatoriale', NULL),
    (25617, 'Guyana', NULL),
    (25618, 'Guyane', NULL),
    (25619, 'Haïti', NULL),
    (25620, 'Honduras', NULL),
    (25621, 'Hong kong', NULL),
    (25622, 'Hongrie', NULL),
    (25623, 'Iles caïmans', NULL),
    (25624, 'Iles cook', NULL),
    (25625, 'Iles mariannes', NULL),
    (25626, 'Iles marshall', NULL),
    (25627, 'Iles salomon', NULL),
    (25628, 'Iles vierges britanniques', NULL),
    (25629, 'Iles vierges us', NULL),
    (25630, 'Inde', NULL),
    (25631, 'Indonésie', NULL),
    (25632, 'Irak', NULL),
    (25633, 'Iran', NULL),
    (25634, 'Irlande', NULL),
    (25635, 'Islande', NULL),
    (25636, 'Israël', NULL),
    (25637, 'Italie', NULL),
    (25638, 'Jamaïque', NULL),
    (25639, 'Japon', NULL),
    (25640, 'Jordanie', NULL),
    (25641, 'Kazakhstan', NULL),
    (25642, 'Kenya', NULL),
    (25643, 'Kirghizistan', NULL),
    (25644, 'Kiribati', NULL),
    (25645, 'Kosovo', NULL),
    (25646, 'Koweït', NULL),
    (25647, 'Laos', NULL),
    (25648, 'Lesotho', NULL),
    (25649, 'Lettonie', NULL),
    (25650, 'Liban', NULL),
    (25651, 'Libéria', NULL),
    (25652, 'Libye', NULL),
    (25653, 'Lituanie', NULL),
    (25654, 'Luxembourg', NULL),
    (25655, 'Macédoine', NULL),
    (25656, 'Madagascar', NULL),
    (25657, 'Madère', NULL),
    (25658, 'Malaisie', NULL),
    (25659, 'Malawi', NULL),
    (25660, 'Maldives', NULL),
    (25661, 'Mali', NULL),
    (25662, 'Malte', NULL),
    (25663, 'Maroc', NULL),
    (25664, 'Martinique', NULL),
    (25665, 'Maurice', NULL),
    (25666, 'Mauritanie', NULL),
    (25667, 'Mayotte', NULL),
    (25668, 'Mexique', NULL),
    (25669, 'Micronésie', NULL),
    (25670, 'Moldavie', NULL),
    (25671, 'Monaco', NULL),
    (25672, 'Mongolie', NULL),
    (25673, 'Monserrat', NULL),
    (25674, 'Monténégro', NULL),
    (25675, 'Mozambique', NULL),
    (25676, 'Myanmar', NULL),
    (25677, 'Namibie', NULL),
    (25678, 'Nauru', NULL),
    (25679, 'Népal', NULL),
    (25680, 'Nicaragua', NULL),
    (25681, 'Niger', NULL),
    (25682, 'Nigéria', NULL),
    (25683, 'Niue', NULL),
    (25684, 'Norvège', NULL),
    (25685, 'Nouvelle-calédonie', NULL),
    (25686, 'Nouvelle-zélande', NULL),
    (25687, 'Oman', NULL),
    (25688, 'Ouganda', NULL),
    (25689, 'Ouzbékistan', NULL),
    (25690, 'Pakistan', NULL),
    (25691, 'Palau', NULL),
    (25692, 'Palestine', NULL),
    (25693, 'Panama', NULL),
    (25694, 'Papouasie nouvelle-guinée', NULL),
    (25695, 'Paraguay', NULL),
    (25696, 'Pays-bas', NULL),
    (25697, 'Pérou', NULL),
    (25698, 'Philippines', NULL),
    (25699, 'Pologne', NULL),
    (25700, 'Polynésie française', NULL),
    (25701, 'Porto rico', NULL),
    (25702, 'Portugal', NULL),
    (25703, 'Qatar', NULL),
    (25704, 'Rép. centrafricaine', NULL),
    (25705, 'République dominicaine', NULL),
    (25706, 'République tchèque', NULL),
    (25707, 'Réunion', NULL),
    (25708, 'Roumanie', NULL),
    (25709, 'Royaume-uni', NULL),
    (25710, 'Russie', NULL),
    (25711, 'Rwanda', NULL),
    (25712, 'Sahara occidental', NULL),
    (25713, 'Saint kitts et nevis', NULL),
    (25714, 'Saint vincent et grenadines', NULL),
    (25715, 'Sainte lucie', NULL),
    (25716, 'Salvador', NULL),
    (25717, 'Samoa occ.', NULL),
    (25718, 'Sao tome et principe', NULL),
    (25719, 'Sénégal', NULL),
    (25720, 'Serbie', NULL),
    (25721, 'Seychelles', NULL),
    (25722, 'Sierra-leone', NULL),
    (25723, 'Singapour', NULL),
    (25724, 'Slovaquie', NULL),
    (25725, 'Slovénie', NULL),
    (25726, 'Somalie', NULL),
    (25727, 'Soudan', NULL),
    (25728, 'Sri lanka', NULL),
    (25729, 'Suède', NULL),
    (25730, 'Suisse', NULL),
    (25731, 'Surinam', NULL),
    (25732, 'Swaziland', NULL),
    (25733, 'Syrie', NULL),
    (25734, 'Tadjikistan', NULL),
    (25735, 'Taïwan', NULL),
    (25736, 'Tanzanie', NULL),
    (25737, 'Tchad', NULL),
    (25738, 'Thaïlande', NULL),
    (25739, 'Tibet', NULL),
    (25740, 'Timor oriental', NULL),
    (25741, 'Togo', NULL),
    (25742, 'Tokelau', NULL),
    (25743, 'Tonga', NULL),
    (25744, 'Trinité et tobago', NULL),
    (25745, 'Tunisie', NULL),
    (25746, 'Turkménistan', NULL),
    (25747, 'Turks et caicos', NULL),
    (25748, 'Turquie', NULL),
    (25749, 'Tuvalu', NULL),
    (25750, 'Ukraine', NULL),
    (25751, 'Uruguay', NULL),
    (25752, 'Vanuatu', NULL),
    (25753, 'Vénézuela', NULL),
    (25754, 'Vietnam', NULL),
    (25755, 'Yémen', NULL),
    (25756, 'Zaïre', NULL),
    (25757, 'Zambie', NULL),
    (25758, 'Zimbabwe', NULL);
