ALTER TABLE `sys_country` ADD COLUMN `cnty_name_en` varchar(80) DEFAULT NULL;
UPDATE `sys_country` set `cnty_name_en` = `cnty_name`;
UPDATE sys_country SET cnty_name_en = 'South africa' WHErE cnty_id = 25535;
UPDATE sys_country SET cnty_name_en = 'Albania' WHErE cnty_id = 25536;
UPDATE sys_country SET cnty_name_en = 'Germany' WHErE cnty_id = 25538;
UPDATE sys_country SET cnty_name_en = 'Antigua and barbuda' WHErE cnty_id = 25541;
UPDATE sys_country SET cnty_name_en = 'Saudi arabia' WHErE cnty_id = 25543;
UPDATE sys_country SET cnty_name_en = 'Argentina' WHErE cnty_id = 25544;
UPDATE sys_country SET cnty_name_en = 'Australia' WHErE cnty_id = 25547;
UPDATE sys_country SET cnty_name_en = 'Austria' WHErE cnty_id = 25548;
UPDATE sys_country SET cnty_name_en = 'Barbados' WHErE cnty_id = 25553;
UPDATE sys_country SET cnty_name_en = 'Belgium' WHErE cnty_id = 25556;
UPDATE sys_country SET cnty_name_en = 'Bermuda' WHErE cnty_id = 25559;
UPDATE sys_country SET cnty_name_en = 'Bhutan' WHErE cnty_id = 25560;
UPDATE sys_country SET cnty_name_en = 'Burma - myanmar' WHErE cnty_id = 25562;
UPDATE sys_country SET cnty_name_en = 'Bolivia' WHErE cnty_id = 25563;
UPDATE sys_country SET cnty_name_en = 'Bulgaria' WHErE cnty_id = 25568;
UPDATE sys_country SET cnty_name_en = 'Cambodia' WHErE cnty_id = 25571;
UPDATE sys_country SET cnty_name_en = 'Cameroon' WHErE cnty_id = 25572;
UPDATE sys_country SET cnty_name_en = 'Canary' WHErE cnty_id = 25574;
UPDATE sys_country SET cnty_name_en = 'Cape verde' WHErE cnty_id = 25575;
UPDATE sys_country SET cnty_name_en = 'Central' WHErE cnty_id = 25576;
UPDATE sys_country SET cnty_name_en = 'Chile' WHErE cnty_id = 25577;
UPDATE sys_country SET cnty_name_en = 'China' WHErE cnty_id = 25578;
UPDATE sys_country SET cnty_name_en = 'Cyprus' WHErE cnty_id = 25579;
UPDATE sys_country SET cnty_name_en = 'Colombia' WHErE cnty_id = 25580;
UPDATE sys_country SET cnty_name_en = 'Comoros' WHErE cnty_id = 25581;
UPDATE sys_country SET cnty_name_en = 'Ivory coast' WHErE cnty_id = 25587;
UPDATE sys_country SET cnty_name_en = 'Croatia' WHErE cnty_id = 25588;
UPDATE sys_country SET cnty_name_en = 'Denmark' WHErE cnty_id = 25590;
UPDATE sys_country SET cnty_name_en = 'Egypt' WHErE cnty_id = 25593;
UPDATE sys_country SET cnty_name_en = 'United arab emirates' WHErE cnty_id = 25595;
UPDATE sys_country SET cnty_name_en = 'Ecuador' WHErE cnty_id = 25596;
UPDATE sys_country SET cnty_name_en = 'Spain' WHErE cnty_id = 25598;
UPDATE sys_country SET cnty_name_en = 'Estonia' WHErE cnty_id = 25599;
UPDATE sys_country SET cnty_name_en = 'Andorra' WHErE cnty_id = 25600;
UPDATE sys_country SET cnty_name_en = 'Usa' WHErE cnty_id = 25601;
UPDATE sys_country SET cnty_name_en = 'Ethiopia' WHErE cnty_id = 25602;
UPDATE sys_country SET cnty_name_en = 'Fiji' WHErE cnty_id = 25603;
UPDATE sys_country SET cnty_name_en = 'Finland' WHErE cnty_id = 25604;
UPDATE sys_country SET cnty_name_en = 'Gambia' WHErE cnty_id = 25607;
UPDATE sys_country SET cnty_name_en = 'Grenada' WHErE cnty_id = 25611;
UPDATE sys_country SET cnty_name_en = 'Guyana' WHErE cnty_id = 25618;
UPDATE sys_country SET cnty_name_en = 'Hungary' WHErE cnty_id = 25622;
UPDATE sys_country SET cnty_name_en = 'Cook islands' WHErE cnty_id = 25624;
UPDATE sys_country SET cnty_name_en = 'Mariana islands' WHErE cnty_id = 25625;
UPDATE sys_country SET cnty_name_en = 'Marshall islands' WHErE cnty_id = 25626;
UPDATE sys_country SET cnty_name_en = 'Solomon islands' WHErE cnty_id = 25627;
UPDATE sys_country SET cnty_name_en = 'British virgin islands' WHErE cnty_id = 25628;
UPDATE sys_country SET cnty_name_en = 'Us virgin islands' WHErE cnty_id = 25629;
UPDATE sys_country SET cnty_name_en = 'India' WHErE cnty_id = 25630;
UPDATE sys_country SET cnty_name_en = 'Iraq' WHErE cnty_id = 25632;
UPDATE sys_country SET cnty_name_en = 'Ireland' WHErE cnty_id = 25634;
UPDATE sys_country SET cnty_name_en = 'Iceland' WHErE cnty_id = 25635;
UPDATE sys_country SET cnty_name_en = 'Italy' WHErE cnty_id = 25637;
UPDATE sys_country SET cnty_name_en = 'Japan' WHErE cnty_id = 25639;
UPDATE sys_country SET cnty_name_en = 'Jordan' WHErE cnty_id = 25640;
UPDATE sys_country SET cnty_name_en = 'Kyrgyzstan' WHErE cnty_id = 25643;
UPDATE sys_country SET cnty_name_en = 'Latvia' WHErE cnty_id = 25649;
UPDATE sys_country SET cnty_name_en = 'Lebanon' WHErE cnty_id = 25650;
UPDATE sys_country SET cnty_name_en = 'Libya' WHErE cnty_id = 25652;
UPDATE sys_country SET cnty_name_en = 'Lithuania' WHErE cnty_id = 25653;
UPDATE sys_country SET cnty_name_en = 'Malaysia' WHErE cnty_id = 25658;
UPDATE sys_country SET cnty_name_en = 'Malta' WHErE cnty_id = 25662;
UPDATE sys_country SET cnty_name_en = 'Morocco' WHErE cnty_id = 25663;
UPDATE sys_country SET cnty_name_en = 'Mauritania' WHErE cnty_id = 25666;
UPDATE sys_country SET cnty_name_en = 'Mexico' WHErE cnty_id = 25668;
UPDATE sys_country SET cnty_name_en = 'Moldova' WHErE cnty_id = 25670;
UPDATE sys_country SET cnty_name_en = 'Mongolia' WHErE cnty_id = 25672;
UPDATE sys_country SET cnty_name_en = 'Montserrat' WHErE cnty_id = 25673;
UPDATE sys_country SET cnty_name_en = 'Namibia' WHErE cnty_id = 25677;
UPDATE sys_country SET cnty_name_en = 'Uganda' WHErE cnty_id = 25688;
UPDATE sys_country SET cnty_name_en = 'Netherlands' WHErE cnty_id = 25696;
UPDATE sys_country SET cnty_name_en = 'Poland' WHErE cnty_id = 25699;
UPDATE sys_country SET cnty_name_en = 'Puerto rico' WHErE cnty_id = 25701;
UPDATE sys_country SET cnty_name_en = 'Romania' WHErE cnty_id = 25708;
UPDATE sys_country SET cnty_name_en = 'United kingdom' WHErE cnty_id = 25709;
UPDATE sys_country SET cnty_name_en = 'Russia' WHErE cnty_id = 25710;
UPDATE sys_country SET cnty_name_en = 'Western sahara' WHErE cnty_id = 25712;
UPDATE sys_country SET cnty_name_en = 'Saint kitts and nevis' WHErE cnty_id = 25713;
UPDATE sys_country SET cnty_name_en = 'Saint vincent and grenadines' WHErE cnty_id = 25714;
UPDATE sys_country SET cnty_name_en = 'St. lucia' WHErE cnty_id = 25715;
UPDATE sys_country SET cnty_name_en = 'Sao tome and principe' WHErE cnty_id = 25718;
UPDATE sys_country SET cnty_name_en = 'Serbia' WHErE cnty_id = 25720;
UPDATE sys_country SET cnty_name_en = 'Sierra leone-' WHErE cnty_id = 25722;
UPDATE sys_country SET cnty_name_en = 'Singapore' WHErE cnty_id = 25723;
UPDATE sys_country SET cnty_name_en = 'Slovakia' WHErE cnty_id = 25724;
UPDATE sys_country SET cnty_name_en = 'Somalia' WHErE cnty_id = 25726;
UPDATE sys_country SET cnty_name_en = 'Sudan' WHErE cnty_id = 25727;
UPDATE sys_country SET cnty_name_en = 'Switzerland' WHErE cnty_id = 25730;
UPDATE sys_country SET cnty_name_en = 'Suriname' WHErE cnty_id = 25731;
UPDATE sys_country SET cnty_name_en = 'Syria' WHErE cnty_id = 25733;
UPDATE sys_country SET cnty_name_en = 'Tajikistan' WHErE cnty_id = 25734;
UPDATE sys_country SET cnty_name_en = 'Tanzania' WHErE cnty_id = 25736;
UPDATE sys_country SET cnty_name_en = 'Chad' WHErE cnty_id = 25737;
UPDATE sys_country SET cnty_name_en = 'East timor' WHErE cnty_id = 25740;
UPDATE sys_country SET cnty_name_en = 'Tunisia' WHErE cnty_id = 25745;
UPDATE sys_country SET cnty_name_en = 'Turks and caicos' WHErE cnty_id = 25747;
UPDATE sys_country SET cnty_name_en = 'Turkey' WHErE cnty_id = 25748;
UPDATE sys_country SET cnty_name_en = 'Zambia' WHErE cnty_id = 25757;
