CREATE TABLE `asso_contract` (
  `ct_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Identifiant du contrat',
  `brk_id` bigint(20) unsigned NOT NULL COMMENT 'Identifiant du broker',
  `ct_code` varchar(20) NOT NULL COMMENT 'Numéro de contrat AAAA.nn',
  `site_id` bigint(20) unsigned NOT NULL COMMENT 'Identifiant du site',
  `ct_from` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Date de début',
  `ct_to` timestamp NULL DEFAULT NULL COMMENT 'Date de fin',
  `ct_duration` varchar(20) DEFAULT NULL COMMENT 'Variable : contract_duration',
  `ct_install_amount` decimal(16,5) DEFAULT NULL COMMENT 'Montant à l''installation',
  `ct_recur_amount` decimal(16,5) DEFAULT NULL COMMENT 'Montant récurrent (annuel, ...)',
  `ct_address_1` varchar(80) DEFAULT NULL COMMENT 'Ligne adresse 1',
  `ct_address_2` varchar(80) DEFAULT NULL COMMENT 'Ligne adresse 2',
  `ct_address_3` varchar(80) DEFAULT NULL COMMENT 'Ligne adresse 3',
  `ct_cp` varchar(20) DEFAULT NULL COMMENT 'Code postal',
  `ct_town` varchar(80) DEFAULT NULL COMMENT 'Ville',
  `cnty_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Identifiant du pays',
  `ctx1_cli_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Identifiant du premier contact',
  `ctx2_cli_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Identifiant du second contact',
  PRIMARY KEY (`ct_id`),
  KEY `fk_contract_broker` (`brk_id`),
  KEY `fk_contract_country` (`cnty_id`),
  KEY `fk_contract_site` (`site_id`),
  KEY `fk_contract_client_1` (`ctx1_cli_id`),
  KEY `fk_contract_client_2` (`ctx2_cli_id`),
  CONSTRAINT `fk_contract_client_1` FOREIGN KEY (`ctx1_cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_contract_client_2` FOREIGN KEY (`ctx2_cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_contract_site` FOREIGN KEY (`site_id`) REFERENCES `asso_site` (`site_id`)
);
CREATE TABLE `asso_contract_media` (
  `ctm_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'Identifiant du média du contrat',
  `ct_id` bigint(20) unsigned NOT NULL COMMENT 'Identifiant du contrat',
  `brk_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Identifiant du broker',
  `ctm_code` varchar(20) NOT NULL DEFAULT '' COMMENT 'Code du média',
  `ctm_type` enum('PHOTO','NEWS','HTML','OTHER') NOT NULL DEFAULT 'OTHER' COMMENT 'Type du média',
  `ctm_ts` timestamp NULL DEFAULT NULL COMMENT 'Date du média',
  `ctm_from` timestamp NULL DEFAULT NULL COMMENT 'Début de validité',
  `ctm_to` timestamp NULL DEFAULT NULL COMMENT 'Fin de validité',
  `ctm_text` longtext DEFAULT NULL COMMENT 'Texte si type NEWS, HTML',
  `ctm_short_text` text DEFAULT NULL COMMENT 'Texte court avec ... si type NEWS, HTML',
  `ctm_blob` longblob DEFAULT NULL COMMENT 'Blob si type PHOTO, OTHER',
  `ctm_short_blob` blob DEFAULT NULL COMMENT 'Vignette si type PHOTO',
  `lang_id` bigint(20) unsigned DEFAULT NULL COMMENT 'Identifiant de la langue',
  `ctm_order` int(11) DEFAULT NULL COMMENT 'Ordre',
  `ctm_title` varchar(255) DEFAULT NULL COMMENT 'Nom du document',
  `ctm_public` tinyint(1) DEFAULT 1 COMMENT 'Document public ?',
  `ctm_desc` text DEFAULT NULL COMMENT 'Description du média',
  PRIMARY KEY (`ctm_id`),
  KEY `fk_contract_media_contract` (`ct_id`),
  KEY `fk_contract_media_lang` (`lang_id`),
  KEY `fk_contract_media_broker` (`brk_id`),
  CONSTRAINT `fk_contract_media_contract` FOREIGN KEY (`ct_id`) REFERENCES `asso_contract` (`ct_id`)
);
ALTER TABLE `asso_cause_media` ADD COLUMN `caum_desc` TEXT NULL AFTER `caum_public`;
ALTER TABLE `asso_site_media` ADD COLUMN `sitm_desc` TEXT NULL AFTER `sitm_title`;
