CREATE TABLE `crm_client_category` (
  `clic_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `clic_code` varchar(20) DEFAULT NULL,
  `clic_name` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`clic_id`),
  KEY `fk_client_category_broker` (`brk_id`)
);
CREATE TABLE `crm_client_type` (
  `clit_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `clit_name` varchar(80) NOT NULL DEFAULT '',
  `clit_code` varchar(20) DEFAULT NULL COMMENT 'cents',
  `clit_string_1` tinyint(1) NOT NULL DEFAULT 0,
  `clit_string_2` tinyint(1) NOT NULL DEFAULT 0,
  `clit_string_3` tinyint(1) NOT NULL DEFAULT 0,
  `clit_string_4` tinyint(1) NOT NULL DEFAULT 0,
  `clit_number_1` tinyint(1) NOT NULL DEFAULT 0,
  `clit_number_2` tinyint(1) NOT NULL DEFAULT 0,
  `clit_number_3` tinyint(1) NOT NULL DEFAULT 0,
  `clit_number_4` tinyint(1) NOT NULL DEFAULT 0,
  `clit_date_1` tinyint(1) NOT NULL DEFAULT 0,
  `clit_date_2` tinyint(1) NOT NULL DEFAULT 0,
  `clit_date_3` tinyint(1) NOT NULL DEFAULT 0,
  `clit_date_4` tinyint(1) NOT NULL DEFAULT 0,
  `clit_text_1` tinyint(1) NOT NULL DEFAULT 0,
  `clit_text_2` tinyint(1) NOT NULL DEFAULT 0,
  `clit_text_3` tinyint(1) NOT NULL DEFAULT 0,
  `clit_text_4` tinyint(1) NOT NULL DEFAULT 0,
  `clit_bool_1` tinyint(1) NOT NULL DEFAULT 0,
  `clit_bool_2` tinyint(1) NOT NULL DEFAULT 0,
  `clit_bool_3` tinyint(1) NOT NULL DEFAULT 0,
  `clit_bool_4` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`clit_id`),
  KEY `fk_cause_type_broker` (`brk_id`)
);
CREATE TABLE `crm_client_type_data` (
  `clitd_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `clit_id` bigint(20) unsigned NOT NULL,
  `clitd_code` varchar(20) DEFAULT NULL,
  `clitd_name` varchar(80) DEFAULT NULL,
  `clitd_type` enum('STRING','INTEGER','DATE','TEXT') NOT NULL DEFAULT 'STRING',
  `clitd_required` int(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`clitd_id`),
  KEY `fk_cause_type_data_cause_type` (`clit_id`),
  CONSTRAINT `fk_client_type_data_client_type` FOREIGN KEY (`clit_id`) REFERENCES `crm_client_type` (`clit_id`)
);
CREATE TABLE `crm_client` (
  `cli_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `clic_id` bigint(20) unsigned DEFAULT NULL,
  `clit_id` bigint(20) unsigned NOT NULL,
  `cli_gender` varchar(10) DEFAULT NULL,
  `cli_firstname` varchar(80) DEFAULT '',
  `cli_lastname` varchar(80) DEFAULT NULL,
  `cli_address1` varchar(80) DEFAULT NULL,
  `cli_address2` varchar(80) DEFAULT NULL,
  `cli_address3` varchar(80) DEFAULT NULL,
  `cli_cp` varchar(20) DEFAULT NULL,
  `cli_town` varchar(80) DEFAULT NULL,
  `cnty_id` bigint(20) unsigned DEFAULT NULL,
  `cli_active` int(1) NOT NULL DEFAULT 1,
  `lang_id` bigint(20) unsigned DEFAULT NULL,
  `cli_prefs` longtext DEFAULT NULL,
  `cli_avatar` blob DEFAULT NULL,
  `cli_phone_home` varchar(80) DEFAULT NULL,
  `cli_phone_gsm` varchar(80) DEFAULT NULL,
  `cli_desc` text DEFAULT NULL,
  `cli_email` varchar(255) DEFAULT NULL,
  `cli_email_2` varchar(255) DEFAULT NULL,
  `cli_email_refused` varchar(255) DEFAULT NULL,
  `cli_receipt` tinyint(1) DEFAULT 1,
  `cli_certificat` tinyint(1) DEFAULT 1,
  `cli_extern_id` varchar(20) DEFAULT NULL,
  `cli_sponsor_id` bigint(20) unsigned DEFAULT NULL,
  `last_don_id` bigint(20) unsigned DEFAULT NULL,
  `cli_string_1` varchar(255) DEFAULT NULL,
  `cli_string_2` varchar(255) DEFAULT NULL,
  `cli_string_3` varchar(255) DEFAULT NULL,
  `cli_string_4` varchar(255) DEFAULT NULL,
  `cli_number_1` int(10) DEFAULT NULL,
  `cli_number_2` int(10) DEFAULT NULL,
  `cli_number_3` int(10) DEFAULT NULL,
  `cli_number_4` int(10) DEFAULT NULL,
  `cli_date_1` timestamp NULL DEFAULT NULL,
  `cli_date_2` timestamp NULL DEFAULT NULL,
  `cli_date_3` timestamp NULL DEFAULT NULL,
  `cli_date_4` timestamp NULL DEFAULT NULL,
  `cli_text_1` longtext DEFAULT NULL,
  `cli_text_2` longtext DEFAULT NULL,
  `cli_text_3` longtext DEFAULT NULL,
  `cli_text_4` longtext DEFAULT NULL,
  `cli_bool_1` tinyint(1) DEFAULT NULL,
  `cli_bool_2` tinyint(1) DEFAULT NULL,
  `cli_bool_3` tinyint(1) DEFAULT NULL,
  `cli_bool_4` tinyint(1) DEFAULT NULL,
  `cli_display_site` tinyint(1) NOT NULL DEFAULT 1,
  `cli_send_news` tinyint(1) NOT NULL DEFAULT 1,
  `cli_coord` varchar(80) DEFAULT NULL,
  `cli_siren` varchar(80) DEFAULT NULL,
  `cli_siret` varchar(80) DEFAULT NULL,
  PRIMARY KEY (`cli_id`),
  KEY `fk_client_country` (`cnty_id`),
  KEY `fk_client_broker` (`brk_id`),
  KEY `fk_client_client_type` (`clit_id`),
  KEY `fk_client_client_category` (`clic_id`),
  KEY `ix_client_fullname` (`cli_firstname`,`cli_lastname`),
  KEY `fk_client_donation` (`last_don_id`),
  CONSTRAINT `fk_client_client_category` FOREIGN KEY (`clic_id`) REFERENCES `crm_client_category` (`clic_id`),
  CONSTRAINT `fk_client_client_type` FOREIGN KEY (`clit_id`) REFERENCES `crm_client_type` (`clit_id`)
);
CREATE TABLE `crm_client_data` (
  `cld_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `cli_id` bigint(20) unsigned NOT NULL,
  `clitd_id` bigint(20) unsigned NOT NULL,
  `cld_valc` varchar(256) DEFAULT NULL,
  `cld_valt` longtext DEFAULT NULL,
  `cld_vali` int(11) DEFAULT NULL,
  `cld_vald` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`cld_id`),
  KEY `fk_client_data_client` (`cli_id`),
  KEY `fk_client_data_client_type_data` (`clitd_id`),
  CONSTRAINT `fk_client_data_client` FOREIGN KEY (`cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_client_data_client_type_data` FOREIGN KEY (`clitd_id`) REFERENCES `crm_client_type_data` (`clitd_id`)
);
CREATE TABLE `asso_config` (
  `acfg_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `acfg_code` varchar(32) NOT NULL DEFAULT '',
  `acfg_value` varchar(256) DEFAULT NULL,
  PRIMARY KEY (`acfg_id`),
  KEY `fk_config_broker` (`brk_id`)
);
CREATE TABLE `asso_data` (
  `data_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `data_name` varchar(80) DEFAULT NULL,
  `data_code` varchar(20) NOT NULL DEFAULT '',
  `data_type` enum('STRING','TEXT','NUMBER','BOOLEAN','DATE','DATETIME','LIST') NOT NULL DEFAULT 'STRING',
  `data_from` timestamp NULL DEFAULT NULL,
  `data_to` timestamp NULL DEFAULT NULL,
  `data_content` longtext DEFAULT NULL,
  PRIMARY KEY (`data_id`),
  KEY `fk_data_broker` (`brk_id`)
);
CREATE TABLE `asso_file` (
  `file_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `file_blob` longblob DEFAULT NULL,
  `file_type` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`file_id`),
  KEY `fk_file_broker` (`brk_id`)
);
CREATE TABLE `asso_payment_type` (
  `ptyp_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `ptyp_code` varchar(20) DEFAULT NULL,
  `ptyp_name` varchar(80) DEFAULT NULL,
  `ptyp_receipt` tinyint(1) NOT NULL DEFAULT 1,
  `ptyp_from` timestamp NULL DEFAULT NULL,
  `ptyp_to` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`ptyp_id`),
  UNIQUE KEY `ix_payment_type_ptyp_name` (`ptyp_name`,`brk_id`,`ptyp_to`),
  KEY `fk_payment_type_broker` (`brk_id`)
);
CREATE TABLE `asso_session` (
  `sess_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `sess_name` varchar(255) DEFAULT NULL,
  `sess_exercice` int(4) DEFAULT NULL,
  `sess_status` enum('OPEN','CLOSED','VALIDATION') NOT NULL DEFAULT 'OPEN',
  `sess_type` enum('STANDARD','CORRECTION') NOT NULL DEFAULT 'STANDARD',
  PRIMARY KEY (`sess_id`)
);
CREATE TABLE `asso_sickness` (
  `sick_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `sick_name` varchar(255) NOT NULL DEFAULT '',
  `sick_desc` longtext DEFAULT NULL,
  `sick_duration` int(11) DEFAULT NULL,
  `sick_type` enum('OTHER','B','MRC','MDO') NOT NULL DEFAULT 'OTHER',
  `sick_freq` int(11) DEFAULT NULL,
  `sick_spread` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`sick_id`),
  KEY `fk_sickness_broker` (`brk_id`)
);
CREATE TABLE `asso_site_type` (
  `sitt_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `sitt_name` varchar(80) DEFAULT NULL,
  `sitt_pattern` varchar(255) DEFAULT NULL,
  `sitt_mask` varchar(255) DEFAULT NULL,
  `sitt_string_1` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_string_2` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_string_3` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_string_4` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_string_5` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_string_6` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_string_7` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_string_8` tinyint(1) DEFAULT NULL,
  `sitt_number_1` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_number_2` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_number_3` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_number_4` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_number_5` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_number_6` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_date_1` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_date_2` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_date_3` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_date_4` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_text_1` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_text_2` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_text_3` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_text_4` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_bool_1` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_bool_2` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_bool_3` tinyint(1) NOT NULL DEFAULT 0,
  `sitt_bool_4` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`sitt_id`),
  UNIQUE KEY `ix_site_type_sitt_name` (`sitt_name`,`brk_id`),
  KEY `fk_site_type_broker` (`brk_id`)
);
CREATE TABLE `asso_site_type_data` (
  `sittd_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `sitt_id` bigint(20) unsigned NOT NULL,
  `data_id` bigint(20) unsigned NOT NULL,
  `sittd_value` varchar(256) DEFAULT NULL,
  `sittd_position` int(11) DEFAULT NULL,
  `sittd_from` timestamp NULL DEFAULT NULL,
  `sittd_to` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`sittd_id`),
  KEY `fk_site_type_data_site_type` (`sitt_id`),
  KEY `fk_site_type_data_data` (`data_id`),
  CONSTRAINT `fk_site_type_data_data` FOREIGN KEY (`data_id`) REFERENCES `asso_data` (`data_id`),
  CONSTRAINT `fk_site_type_data_site_type` FOREIGN KEY (`sitt_id`) REFERENCES `asso_site_type` (`sitt_id`)
);
CREATE TABLE `asso_site` (
  `site_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `sitt_id` bigint(20) unsigned NOT NULL,
  `site_name` varchar(80) NOT NULL DEFAULT '',
  `site_from` timestamp NULL DEFAULT NULL,
  `site_to` timestamp NULL DEFAULT NULL,
  `site_code` varchar(32) DEFAULT NULL,
  `site_address1` varchar(80) DEFAULT NULL,
  `site_address2` varchar(80) DEFAULT NULL,
  `site_address3` varchar(80) DEFAULT NULL,
  `site_cp` varchar(20) DEFAULT NULL,
  `site_town` varchar(80) DEFAULT NULL,
  `owner_cli_id` bigint(20) unsigned DEFAULT NULL,
  `sanit_cli_id` bigint(20) unsigned DEFAULT NULL,
  `parent_site_id` bigint(20) unsigned DEFAULT NULL,
  `site_area` int(11) DEFAULT NULL,
  `site_position` int(11) DEFAULT NULL,
  `site_plots` text DEFAULT NULL,
  `site_left` bigint(20) unsigned DEFAULT NULL,
  `site_right` bigint(20) unsigned DEFAULT NULL,
  `site_level` bigint(20) unsigned DEFAULT NULL,
  `site_string_1` varchar(255) DEFAULT NULL,
  `site_string_2` varchar(255) DEFAULT NULL,
  `site_string_3` varchar(255) DEFAULT NULL,
  `site_string_4` varchar(255) DEFAULT NULL,
  `site_string_5` varchar(255) DEFAULT NULL,
  `site_string_6` varchar(255) DEFAULT NULL,
  `site_string_7` varchar(255) DEFAULT NULL,
  `site_string_8` varchar(255) DEFAULT NULL,
  `site_number_1` int(10) DEFAULT NULL,
  `site_number_2` int(10) DEFAULT NULL,
  `site_number_3` int(10) DEFAULT NULL,
  `site_number_4` int(10) DEFAULT NULL,
  `site_number_5` int(11) DEFAULT NULL,
  `site_number_6` int(11) DEFAULT NULL,
  `site_date_1` timestamp NULL DEFAULT NULL,
  `site_date_2` timestamp NULL DEFAULT NULL,
  `site_date_3` timestamp NULL DEFAULT NULL,
  `site_date_4` timestamp NULL DEFAULT NULL,
  `site_text_1` longtext DEFAULT NULL,
  `site_text_2` longtext DEFAULT NULL,
  `site_text_3` longtext DEFAULT NULL,
  `site_text_4` longtext DEFAULT NULL,
  `site_bool_1` tinyint(1) DEFAULT NULL,
  `site_bool_2` tinyint(1) DEFAULT NULL,
  `site_bool_3` tinyint(1) DEFAULT NULL,
  `site_bool_4` tinyint(1) DEFAULT NULL,
  `site_coord` varchar(80) DEFAULT NULL,
  `site_code_ex` varchar(32) DEFAULT NULL,
  `site_desc` longtext DEFAULT NULL,
  `site_conform` tinyint(1) NOT NULL DEFAULT 1,
  `site_conform_text` text DEFAULT NULL,
  PRIMARY KEY (`site_id`),
  UNIQUE KEY `ix_site_site_name` (`site_name`,`site_to`,`brk_id`),
  KEY `fk_site_site_type` (`sitt_id`),
  KEY `fk_site_broker` (`brk_id`),
  KEY `fk_site_owner` (`owner_cli_id`),
  KEY `fk_site_sanitary` (`sanit_cli_id`),
  KEY `fk_site_parent` (`parent_site_id`),
  CONSTRAINT `fk_site_owner` FOREIGN KEY (`owner_cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_site_parent` FOREIGN KEY (`parent_site_id`) REFERENCES `asso_site` (`site_id`),
  CONSTRAINT `fk_site_sanitary` FOREIGN KEY (`sanit_cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_site_site_type` FOREIGN KEY (`sitt_id`) REFERENCES `asso_site_type` (`sitt_id`)
);
CREATE TABLE `asso_species` (
  `spe_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `spe_name` varchar(255) NOT NULL DEFAULT '',
  `spe_scientific` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`spe_id`),
  UNIQUE KEY `ix_species_name` (`brk_id`,`spe_name`)
);
CREATE TABLE `asso_subspecies` (
  `sspe_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `spe_id` bigint(20) unsigned NOT NULL,
  `sspe_name` varchar(255) NOT NULL DEFAULT '',
  `sspe_scientific` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`sspe_id`),
  KEY `ix_subspecies_name` (`brk_id`,`sspe_name`),
  KEY `fk_subspecies_species` (`spe_id`),
  CONSTRAINT `fk_subspecies_species` FOREIGN KEY (`spe_id`) REFERENCES `asso_species` (`spe_id`)
);
CREATE TABLE `asso_cause_main_type` (
  `camt_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `camt_name` varchar(80) DEFAULT NULL,
  `camt_family` enum('OTHER','NONE','ANIMAL','FOREST','NATURE','ADMINISTRATIV') NOT NULL DEFAULT 'ANIMAL',
  PRIMARY KEY (`camt_id`),
  UNIQUE KEY `ix_cause_main_type_camt_name` (`camt_name`,`brk_id`),
  KEY `fk_cause_main_type_broker` (`brk_id`)
);
CREATE TABLE `asso_cause_type` (
  `caut_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `camt_id` bigint(20) unsigned DEFAULT NULL,
  `caut_name` varchar(80) NOT NULL DEFAULT '',
  `caut_pattern` varchar(255) DEFAULT NULL,
  `caut_mask` varchar(255) DEFAULT NULL,
  `caut_receipt` tinyint(1) NOT NULL DEFAULT 1,
  `caut_max_mnt` int(11) DEFAULT NULL COMMENT 'cents',
  `caut_min_mnt` int(11) DEFAULT NULL COMMENT 'cents',
  `caut_money` varchar(3) NOT NULL DEFAULT 'EUR',
  `caut_mnt_type` enum('ANNUAL','MAXIMUM','OTHER') NOT NULL DEFAULT 'OTHER',
  `caut_certificat` tinyint(1) NOT NULL DEFAULT 1,
  `caut_donation` enum('ALL','ONCE','REGULAR') NOT NULL DEFAULT 'ALL',
  `caut_once_duration` enum('1Y','1M','INFINITE') NOT NULL DEFAULT 'INFINITE',
  `caut_regular_duration` enum('1Y','1M','INFINITE') NOT NULL DEFAULT 'INFINITE',
  `caut_news` tinyint(1) NOT NULL DEFAULT 1,
  `caut_family` enum('OTHER','NONE','ANIMAL','FOREST','NATURE','ADMINISTRATIV') NOT NULL DEFAULT 'OTHER',
  `caut_string_1` tinyint(1) NOT NULL DEFAULT 0,
  `caut_string_2` tinyint(1) NOT NULL DEFAULT 0,
  `caut_string_3` tinyint(1) NOT NULL DEFAULT 0,
  `caut_string_4` tinyint(1) NOT NULL DEFAULT 0,
  `caut_number_1` tinyint(1) NOT NULL DEFAULT 0,
  `caut_number_2` tinyint(1) NOT NULL DEFAULT 0,
  `caut_number_3` tinyint(1) NOT NULL DEFAULT 0,
  `caut_number_4` tinyint(1) NOT NULL DEFAULT 0,
  `caut_date_1` tinyint(1) NOT NULL DEFAULT 0,
  `caut_date_2` tinyint(1) NOT NULL DEFAULT 0,
  `caut_date_3` tinyint(1) NOT NULL DEFAULT 0,
  `caut_date_4` tinyint(1) NOT NULL DEFAULT 0,
  `caut_text_1` tinyint(1) NOT NULL DEFAULT 0,
  `caut_text_2` tinyint(1) NOT NULL DEFAULT 0,
  `caut_text_3` tinyint(1) NOT NULL DEFAULT 0,
  `caut_text_4` tinyint(1) NOT NULL DEFAULT 0,
  `caut_bool_1` tinyint(1) NOT NULL DEFAULT 0,
  `caut_bool_2` tinyint(1) NOT NULL DEFAULT 0,
  `caut_bool_3` tinyint(1) NOT NULL DEFAULT 0,
  `caut_bool_4` tinyint(1) NOT NULL DEFAULT 0,
  `caut_max_weight` decimal(8,2) DEFAULT NULL,
  `caut_max_height` decimal(8,2) DEFAULT NULL,
  `caut_growth_freq` int(11) DEFAULT NULL,
  `caut_growth_graph` longtext DEFAULT NULL,
  PRIMARY KEY (`caut_id`),
  UNIQUE KEY `i1_asso_cause_type` (`caut_name`,`brk_id`),
  UNIQUE KEY `ix_cause_type_caut_name` (`caut_name`,`brk_id`),
  KEY `fk_cause_type_broker` (`brk_id`),
  KEY `fk_cause_type_cause_main_type` (`camt_id`),
  CONSTRAINT `fk_cause_type_cause_main_type` FOREIGN KEY (`camt_id`) REFERENCES `asso_cause_main_type` (`camt_id`)
);
CREATE TABLE `asso_cause` (
  `cau_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `caut_id` bigint(20) unsigned NOT NULL,
  `cau_name` varchar(80) NOT NULL DEFAULT '',
  `cau_desc` longtext DEFAULT NULL,
  `cau_from` timestamp NULL DEFAULT NULL,
  `cau_to` timestamp NULL DEFAULT NULL,
  `cau_public` tinyint(1) NOT NULL DEFAULT 1,
  `cau_available` tinyint(1) NOT NULL DEFAULT 1,
  `sspe_id` bigint(20) unsigned DEFAULT NULL,
  `site_id` bigint(20) unsigned NOT NULL DEFAULT 1,
  `orig_cli_id` bigint(20) unsigned DEFAULT NULL,
  `rais_cli_id` bigint(20) unsigned DEFAULT NULL,
  `cau_mnt` decimal(15,6) DEFAULT NULL COMMENT 'cents',
  `cau_mnt_left` decimal(15,6) DEFAULT NULL,
  `cau_money` varchar(3) DEFAULT 'EUR',
  `cau_code` varchar(32) DEFAULT NULL,
  `cau_family` enum('OTHER','NONE','ANIMAL','FOREST') NOT NULL DEFAULT 'NONE',
  `cau_sex` enum('M','F','OTHER') DEFAULT 'OTHER',
  `cau_year` int(11) DEFAULT NULL,
  `cau_string_1` varchar(255) DEFAULT NULL,
  `cau_string_2` varchar(255) DEFAULT NULL,
  `cau_string_3` varchar(255) DEFAULT NULL,
  `cau_string_4` varchar(255) DEFAULT NULL,
  `cau_number_1` int(10) DEFAULT NULL,
  `cau_number_2` int(10) DEFAULT NULL,
  `cau_number_3` int(10) DEFAULT NULL,
  `cau_number_4` int(10) DEFAULT NULL,
  `cau_date_1` timestamp NULL DEFAULT NULL,
  `cau_date_2` timestamp NULL DEFAULT NULL,
  `cau_date_3` timestamp NULL DEFAULT NULL,
  `cau_date_4` timestamp NULL DEFAULT NULL,
  `cau_text_1` longtext DEFAULT NULL,
  `cau_text_2` longtext DEFAULT NULL,
  `cau_text_3` longtext DEFAULT NULL,
  `cau_text_4` longtext DEFAULT NULL,
  `cau_bool_1` tinyint(1) DEFAULT NULL,
  `cau_bool_2` tinyint(1) DEFAULT NULL,
  `cau_bool_3` tinyint(1) DEFAULT NULL,
  `cau_bool_4` tinyint(1) DEFAULT NULL,
  `cau_coord` varchar(80) DEFAULT NULL,
  `parent1_cau_id` bigint(20) unsigned DEFAULT NULL,
  `parent2_cau_id` bigint(20) unsigned DEFAULT NULL,
  `caum_text_id` bigint(20) unsigned DEFAULT NULL,
  `caum_blob_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`cau_id`),
  UNIQUE KEY `ix_cause_cause_name` (`cau_name`,`brk_id`,`cau_to`),
  KEY `fk_cause_cause_type` (`caut_id`),
  KEY `fk_cause_broker` (`brk_id`),
  KEY `fk_cause_site` (`site_id`),
  KEY `fk_cause_cause_parent1` (`parent1_cau_id`),
  KEY `fk_cause_cause_parent2` (`parent2_cau_id`),
  KEY `fk_cause_proprietary` (`orig_cli_id`),
  KEY `fk_cause_cause_media_blob` (`caum_blob_id`),
  KEY `fk_cause_cause_media_text` (`caum_text_id`),
  KEY `fk_cause_raiser` (`rais_cli_id`),
  KEY `fk_cause_subspecies` (`sspe_id`),
  CONSTRAINT `fk_cause_cause_parent1` FOREIGN KEY (`parent1_cau_id`) REFERENCES `asso_cause` (`cau_id`),
  CONSTRAINT `fk_cause_cause_parent2` FOREIGN KEY (`parent2_cau_id`) REFERENCES `asso_cause` (`cau_id`),
  CONSTRAINT `fk_cause_cause_type` FOREIGN KEY (`caut_id`) REFERENCES `asso_cause_type` (`caut_id`),
  CONSTRAINT `fk_cause_proprietary` FOREIGN KEY (`orig_cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_cause_raiser` FOREIGN KEY (`rais_cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_cause_site` FOREIGN KEY (`site_id`) REFERENCES `asso_site` (`site_id`),
  CONSTRAINT `fk_cause_subspecies` FOREIGN KEY (`sspe_id`) REFERENCES `asso_subspecies` (`sspe_id`)
);
CREATE TABLE `asso_cause_type_data` (
  `cautd_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `caut_id` bigint(20) unsigned NOT NULL,
  `cautd_code` varchar(20) DEFAULT NULL,
  `cautd_name` varchar(80) DEFAULT NULL,
  `cautd_type` enum('I18N','STRING','INTEGER','DATE','TEXT') NOT NULL DEFAULT 'STRING',
  `cautd_required` int(1) NOT NULL DEFAULT 1,
  `cautd_calculation` enum('NONE','AREA','RATE') NOT NULL DEFAULT 'NONE',
  `cautd_operator` varchar(10) DEFAULT NULL,
  `cautd_factor` decimal(16,5) DEFAULT NULL,
  `cautd_currency` varchar(10) DEFAULT '',
  PRIMARY KEY (`cautd_id`),
  KEY `fk_cause_type_data_cause_type` (`caut_id`),
  CONSTRAINT `fk_cause_type_data_cause_type` FOREIGN KEY (`caut_id`) REFERENCES `asso_cause_type` (`caut_id`)
);
CREATE TABLE `asso_cause_data` (
  `caud_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `cau_id` bigint(20) unsigned NOT NULL,
  `cautd_id` bigint(20) unsigned NOT NULL,
  `caud_vals` varchar(256) DEFAULT NULL,
  `caud_valt` longtext DEFAULT NULL,
  `caud_vali` int(11) DEFAULT NULL,
  `caud_vald` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`caud_id`),
  KEY `fk_cause_data_cause` (`cau_id`),
  KEY `fk_cause_data_cause_type_data` (`cautd_id`),
  CONSTRAINT `fk_cause_data_cause` FOREIGN KEY (`cau_id`) REFERENCES `asso_cause` (`cau_id`),
  CONSTRAINT `fk_cause_data_cause_type_data` FOREIGN KEY (`cautd_id`) REFERENCES `asso_cause_type_data` (`cautd_id`)
);
CREATE TABLE `asso_cause_growth` (
  `grow_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `cau_id` bigint(20) unsigned NOT NULL,
  `grow_ts` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `grow_weight` decimal(5,2) DEFAULT NULL,
  `grow_height` decimal(5,2) DEFAULT NULL,
  PRIMARY KEY (`grow_id`),
  KEY `fk_cause_growth_broker` (`brk_id`),
  KEY `fk_cause_growth_cause` (`cau_id`),
  CONSTRAINT `fk_cause_growth_cause` FOREIGN KEY (`cau_id`) REFERENCES `asso_cause` (`cau_id`)
);
CREATE TABLE `asso_cause_link` (
  `caul_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `from_cau_id` bigint(20) unsigned DEFAULT NULL,
  `to_cau_id` bigint(20) unsigned DEFAULT NULL,
  `caul_from` timestamp NULL DEFAULT NULL,
  `caul_to` timestamp NULL DEFAULT NULL,
  `cault_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`caul_id`)
);
CREATE TABLE `asso_cause_link_type` (
  `cault_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `cault_name` varchar(80) NOT NULL DEFAULT '',
  `ref_cault_id` bigint(20) unsigned DEFAULT NULL,
  `brk_id` bigint(20) unsigned NOT NULL,
  `cault_family` enum('OTHER') NOT NULL DEFAULT 'OTHER',
  PRIMARY KEY (`cault_id`)
);
CREATE TABLE `asso_cause_media` (
  `caum_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `cau_id` bigint(20) unsigned NOT NULL,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `caum_code` varchar(20) NOT NULL DEFAULT '',
  `caum_type` enum('PHOTO','NEWS','HTML','OTHER') NOT NULL DEFAULT 'OTHER',
  `caum_ts` timestamp NULL DEFAULT NULL,
  `caum_from` timestamp NULL DEFAULT NULL,
  `caum_to` timestamp NULL DEFAULT NULL,
  `caum_text` longtext DEFAULT NULL,
  `caum_short_text` text DEFAULT NULL,
  `caum_blob` longblob DEFAULT NULL,
  `caum_short_blob` blob DEFAULT NULL,
  `lang_id` bigint(20) unsigned DEFAULT NULL,
  `caum_order` int(11) DEFAULT NULL,
  `caum_title` varchar(255) DEFAULT NULL,
  `caum_public` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`caum_id`),
  KEY `fk_cause_media_cause` (`cau_id`),
  KEY `fk_cause_media_broker` (`brk_id`),
  KEY `fk_cause_media_lang` (`lang_id`),
  CONSTRAINT `fk_cause_media_cause` FOREIGN KEY (`cau_id`) REFERENCES `asso_cause` (`cau_id`)
);
CREATE TABLE `asso_cause_media_lang` (
  `caml_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `caum_id` bigint(20) unsigned DEFAULT NULL,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `lang_id` bigint(20) unsigned DEFAULT NULL,
  `caml_subject` varchar(255) DEFAULT NULL,
  `caml_blob` longblob DEFAULT NULL,
  `caml_text` longtext DEFAULT NULL,
  PRIMARY KEY (`caml_id`),
  KEY `fk_cause_media_lang_cause_media` (`caum_id`),
  KEY `fk_cause_media_lang_broker` (`brk_id`),
  KEY `fk_cause_media_lang_lang` (`lang_id`),
  CONSTRAINT `fk_cause_media_lang_cause_media` FOREIGN KEY (`caum_id`) REFERENCES `asso_cause_media` (`caum_id`)
);
CREATE TABLE `asso_movement` (
  `move_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `move_from_site_id` bigint(20) unsigned DEFAULT NULL,
  `move_to_site_id` bigint(20) unsigned DEFAULT NULL,
  `move_tr_name` varchar(80) DEFAULT '',
  `move_tr_num` varchar(20) DEFAULT '',
  `move_tr_num2` varchar(20) DEFAULT NULL,
  `move_from` timestamp NULL DEFAULT NULL,
  `move_from_empty` tinyint(1) NOT NULL DEFAULT 0,
  `move_from_type` enum('OTHER','BREEDING','MARKET','COMMERCIAL','ASSEMBLY') NOT NULL DEFAULT 'OTHER',
  `move_from_cli_id` bigint(20) unsigned DEFAULT NULL,
  `move_from_num` varchar(20) DEFAULT NULL,
  `move_from_name` varchar(80) DEFAULT NULL,
  `move_from_address` varchar(80) DEFAULT NULL,
  `move_from_cp` varchar(10) DEFAULT NULL,
  `move_from_town` varchar(80) DEFAULT NULL,
  `move_from_number_1` int(11) DEFAULT NULL,
  `move_from_number_2` int(11) DEFAULT NULL,
  `move_from_number_3` int(11) DEFAULT NULL,
  `move_from_number_4` int(11) DEFAULT NULL,
  `move_from_number_5` int(11) DEFAULT NULL,
  `move_from_number_6` int(11) DEFAULT NULL,
  `move_to` timestamp NULL DEFAULT NULL,
  `move_to_empty` tinyint(1) NOT NULL DEFAULT 0,
  `move_to_type` enum('OTHER','BREEDING','INDIVIDUAL','SLAUGHTERHOUSE','MARKET','COMMERCIAL','ASSEMBLY') NOT NULL DEFAULT 'OTHER',
  `move_to_cli_id` bigint(20) unsigned DEFAULT NULL,
  `move_to_num` varchar(20) DEFAULT NULL,
  `move_to_name` varchar(80) DEFAULT NULL,
  `move_to_address` varchar(80) DEFAULT NULL,
  `move_to_cp` varchar(10) DEFAULT NULL,
  `move_to_town` varchar(80) DEFAULT NULL,
  `move_to_number_1` int(11) DEFAULT NULL,
  `move_to_number_2` int(11) DEFAULT NULL,
  `move_to_number_3` int(11) DEFAULT NULL,
  `move_to_number_4` int(11) DEFAULT NULL,
  `move_to_number_5` int(11) DEFAULT NULL,
  `move_to_number_6` int(11) DEFAULT NULL,
  `move_group_name_1` varchar(20) DEFAULT NULL,
  `move_group_num_1` int(11) DEFAULT NULL,
  `move_group_name_2` varchar(20) DEFAULT NULL,
  `move_group_num_2` int(11) DEFAULT NULL,
  `move_group_name_3` varchar(20) DEFAULT NULL,
  `move_group_num_3` int(11) DEFAULT NULL,
  `move_group_name_4` varchar(20) DEFAULT NULL,
  `move_group_num_4` int(11) DEFAULT NULL,
  `move_desc` longtext DEFAULT NULL,
  `move_blob` longblob DEFAULT NULL,
  PRIMARY KEY (`move_id`),
  KEY `fk_movement_broker` (`brk_id`)
);
CREATE TABLE `asso_cause_movement` (
  `camv_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `cau_id` bigint(20) unsigned NOT NULL,
  `camv_site_from_id` bigint(20) unsigned NOT NULL,
  `camv_site_to_id` bigint(20) unsigned NOT NULL,
  `camv_ts` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `camv_start` timestamp NULL DEFAULT NULL,
  `camv_to` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `camv_comment` longtext DEFAULT NULL,
  `camv_status` enum('OK','WAIT','KO') NOT NULL DEFAULT 'OK',
  `move_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`camv_id`),
  KEY `fk_cause_movement_cause` (`cau_id`),
  KEY `fk_cause_movement_site_from` (`camv_site_from_id`),
  KEY `fk_cause_movement_site_to` (`camv_site_to_id`),
  KEY `fk_cause_movement_broker` (`brk_id`),
  CONSTRAINT `fk_cause_movement_cause` FOREIGN KEY (`cau_id`) REFERENCES `asso_cause` (`cau_id`),
  CONSTRAINT `fk_cause_movement_site_from` FOREIGN KEY (`camv_site_from_id`) REFERENCES `asso_site` (`site_id`),
  CONSTRAINT `fk_cause_movement_site_to` FOREIGN KEY (`camv_site_to_id`) REFERENCES `asso_site` (`site_id`)
);
CREATE TABLE `asso_cause_sickness` (
  `caus_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `cau_id` bigint(20) unsigned NOT NULL,
  `sick_id` bigint(20) unsigned NOT NULL,
  `caus_from` timestamp NULL DEFAULT NULL,
  `caus_to` timestamp NULL DEFAULT NULL,
  `sanitary_id` bigint(20) unsigned DEFAULT NULL,
  `caus_desc` longtext DEFAULT NULL,
  `caus_where` enum('SITE','SANITARY','OTHER') NOT NULL DEFAULT 'SITE',
  `caus_care` enum('DRUG','SANITARY','OTHER') NOT NULL DEFAULT 'OTHER',
  `caus_care_desc` longtext DEFAULT NULL,
  PRIMARY KEY (`caus_id`),
  KEY `fk_cause_sickness_broker` (`brk_id`),
  KEY `fk_cause_sickness_cause` (`cau_id`),
  KEY `fk_cause_sickness_sickness` (`sick_id`),
  KEY `fk_cause_sickness_sanitary` (`sanitary_id`),
  CONSTRAINT `fk_cause_sickness_cause` FOREIGN KEY (`cau_id`) REFERENCES `asso_cause` (`cau_id`),
  CONSTRAINT `fk_cause_sickness_sanitary` FOREIGN KEY (`sanitary_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_cause_sickness_sickness` FOREIGN KEY (`sick_id`) REFERENCES `asso_sickness` (`sick_id`)
);
CREATE TABLE `asso_certificate` (
  `cert_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `cert_ts` timestamp NULL DEFAULT NULL,
  `cli_id` bigint(20) unsigned DEFAULT NULL,
  `cert_gen_ts` timestamp NULL DEFAULT NULL,
  `cert_print_ts` timestamp NULL DEFAULT NULL,
  `cert_fullname` varchar(80) DEFAULT NULL,
  `cert_address1` varchar(80) DEFAULT NULL,
  `cert_address2` varchar(80) DEFAULT NULL,
  `cert_address3` varchar(80) DEFAULT NULL,
  `cert_cp` varchar(20) DEFAULT NULL,
  `cert_town` varchar(80) DEFAULT NULL,
  `lang_id` bigint(20) unsigned DEFAULT NULL,
  `cnty_id` bigint(20) unsigned DEFAULT NULL,
  `cert_email` varchar(255) DEFAULT '',
  `cert_input_mnt` decimal(15,6) DEFAULT NULL,
  `cert_input_money` varchar(3) DEFAULT NULL,
  `cert_output_mnt` decimal(15,6) DEFAULT NULL,
  `cert_output_money` varchar(3) DEFAULT NULL,
  `cert_comment` text DEFAULT NULL,
  `cert_data1` varchar(80) DEFAULT NULL,
  `cert_data2` varchar(80) DEFAULT NULL,
  `file_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`cert_id`),
  KEY `fk_certificate_broker` (`brk_id`),
  KEY `fk_certificate_client` (`cli_id`),
  KEY `fk_certificate_lang` (`lang_id`),
  KEY `fk_certificate_country` (`cnty_id`),
  KEY `fk_certificate_file` (`file_id`),
  CONSTRAINT `fk_certificate_broker` FOREIGN KEY (`brk_id`) REFERENCES `sso_broker` (`brk_id`),
  CONSTRAINT `fk_certificate_client` FOREIGN KEY (`cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_certificate_file` FOREIGN KEY (`file_id`) REFERENCES `asso_file` (`file_id`)
);
CREATE TABLE `asso_donation_origin` (
  `dono_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `dono_ts` timestamp NULL DEFAULT NULL,
  `dono_origin` varchar(255) DEFAULT NULL,
  `dono_comments` longtext DEFAULT NULL,
  `dono_year` int(4) NOT NULL,
  `dono_month` int(2) NOT NULL,
  `dono_day` int(2) NOT NULL DEFAULT 10,
  `dono_status` enum('OK','PENDING','ERROR') NOT NULL DEFAULT 'PENDING',
  PRIMARY KEY (`dono_id`),
  KEY `ix_donation_origin_when` (`brk_id`,`dono_year`,`dono_month`,`dono_day`)
);
CREATE TABLE `asso_sponsorship` (
  `spo_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `cau_id` bigint(20) unsigned DEFAULT NULL,
  `cli_id` bigint(20) unsigned NOT NULL,
  `spo_from` timestamp NULL DEFAULT NULL,
  `spo_to` timestamp NULL DEFAULT NULL,
  `spo_mnt` decimal(15,2) DEFAULT NULL COMMENT 'cents',
  `spo_money` varchar(3) NOT NULL DEFAULT 'EUR',
  `spo_freq` enum('MONTH','YEAR','OTHER') NOT NULL DEFAULT 'OTHER',
  `spo_freq_when` int(4) DEFAULT NULL,
  `spo_freq_detail` varchar(255) DEFAULT NULL,
  `ptyp_id` bigint(20) unsigned NOT NULL,
  `spo_sponsors` text DEFAULT NULL,
  `spo_display_site` tinyint(1) NOT NULL DEFAULT 1,
  `spo_send_news` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`spo_id`),
  KEY `fk_sponsorship_cause` (`cau_id`),
  KEY `fk_sponsorship_client` (`cli_id`),
  KEY `fk_sponsorship_payement_type` (`ptyp_id`),
  KEY `fk_sponsorship_broker` (`brk_id`),
  CONSTRAINT `fk_sponsorship_cause` FOREIGN KEY (`cau_id`) REFERENCES `asso_cause` (`cau_id`),
  CONSTRAINT `fk_sponsorship_client` FOREIGN KEY (`cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_sponsorship_payment_type` FOREIGN KEY (`ptyp_id`) REFERENCES `asso_payment_type` (`ptyp_id`)
);
CREATE TABLE `asso_donation` (
  `don_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `grp_id` bigint(20) unsigned NOT NULL,
  `cli_id` bigint(20) unsigned NOT NULL,
  `cau_id` bigint(20) unsigned DEFAULT NULL,
  `spo_id` bigint(20) unsigned DEFAULT NULL,
  `don_desc` longtext DEFAULT NULL,
  `don_ts` timestamp NULL DEFAULT NULL,
  `don_ask_ts` timestamp NULL DEFAULT NULL,
  `don_real_ts` timestamp NULL DEFAULT NULL,
  `don_end_ts` timestamp NULL DEFAULT NULL,
  `don_status` enum('WAIT','OK','NOK','NEXT') NOT NULL DEFAULT 'WAIT',
  `don_mnt` decimal(15,2) DEFAULT NULL COMMENT 'cents',
  `don_money` varchar(3) DEFAULT 'EUR',
  `don_mnt_input` decimal(15,2) DEFAULT NULL,
  `don_money_input` varchar(3) DEFAULT 'EUR',
  `ptyp_id` bigint(20) unsigned NOT NULL,
  `don_comment` text DEFAULT NULL,
  `don_dstat` timestamp NULL DEFAULT NULL,
  `rec_id` bigint(20) unsigned DEFAULT NULL,
  `cert_id` bigint(20) unsigned DEFAULT NULL,
  `don_sponsors` text DEFAULT NULL,
  `don_display_site` tinyint(1) DEFAULT 1,
  `dono_id` bigint(20) unsigned DEFAULT NULL,
  `sess_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`don_id`),
  KEY `fk_donation_client` (`cli_id`),
  KEY `fk_donation_cause` (`cau_id`),
  KEY `fk_donation_sponsorship` (`spo_id`),
  KEY `fk_donation_payment_type` (`ptyp_id`),
  KEY `fk_donation_broker` (`brk_id`),
  KEY `fk_donation_donation_origin` (`dono_id`),
  KEY `fk_donation_session` (`sess_id`),
  KEY `fk_donation_certificate` (`cert_id`),
  CONSTRAINT `fk_donation_cause` FOREIGN KEY (`cau_id`) REFERENCES `asso_cause` (`cau_id`),
  CONSTRAINT `fk_donation_certificate` FOREIGN KEY (`cert_id`) REFERENCES `asso_certificate` (`cert_id`),
  CONSTRAINT `fk_donation_client` FOREIGN KEY (`cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_donation_donation_origin` FOREIGN KEY (`dono_id`) REFERENCES `asso_donation_origin` (`dono_id`),
  CONSTRAINT `fk_donation_payment_type` FOREIGN KEY (`ptyp_id`) REFERENCES `asso_payment_type` (`ptyp_id`),
  CONSTRAINT `fk_donation_session` FOREIGN KEY (`sess_id`) REFERENCES `asso_session` (`sess_id`),
  CONSTRAINT `fk_donation_sponsorship` FOREIGN KEY (`spo_id`) REFERENCES `asso_sponsorship` (`spo_id`)
);
CREATE TABLE `asso_receipt_type` (
  `rett_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned DEFAULT NULL,
  `rett_name` varchar(80) DEFAULT NULL,
  `rett_last_number` int(11) DEFAULT NULL,
  `rett_regex` text DEFAULT NULL,
  PRIMARY KEY (`rett_id`),
  KEY `fk_receipt_type_broker` (`brk_id`)
);
CREATE TABLE `asso_receipt` (
  `rec_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `cli_id` bigint(20) unsigned NOT NULL,
  `rett_id` bigint(20) unsigned DEFAULT NULL,
  `rec_mode` enum('MANUAL','AUTO') NOT NULL DEFAULT 'MANUAL',
  `rec_ts` timestamp NULL DEFAULT NULL,
  `rec_gen_ts` timestamp NULL DEFAULT NULL,
  `rec_print_ts` timestamp NULL DEFAULT NULL,
  `rec_year` int(11) DEFAULT NULL,
  `rec_number` varchar(20) DEFAULT NULL,
  `rec_mnt` decimal(15,6) DEFAULT NULL,
  `rec_money` varchar(3) DEFAULT 'EUR',
  `rec_fullname` varchar(80) DEFAULT NULL,
  `rec_address1` varchar(80) DEFAULT NULL,
  `rec_address2` varchar(80) DEFAULT NULL,
  `rec_address3` varchar(80) DEFAULT NULL,
  `rec_cp` varchar(80) DEFAULT NULL,
  `rec_town` varchar(80) DEFAULT NULL,
  `cnty_id` bigint(20) unsigned DEFAULT NULL,
  `lang_id` bigint(20) unsigned DEFAULT NULL,
  `rec_email` varchar(255) DEFAULT '',
  `rec_send_method` enum('EMAIL','MANUAL','UNKNOWN') NOT NULL DEFAULT 'MANUAL',
  `rec_mnt_letter` text DEFAULT NULL,
  `file_id` bigint(20) unsigned DEFAULT NULL,
  PRIMARY KEY (`rec_id`),
  KEY `fk_receipt_broker` (`brk_id`),
  KEY `fk_receipt_client` (`cli_id`),
  KEY `fk_receipt_country` (`cnty_id`),
  KEY `fk_receipt_file` (`file_id`),
  KEY `fk_receipt_lang` (`lang_id`),
  KEY `fk_receipt_receipt_type` (`rett_id`),
  CONSTRAINT `fk_receipt_client` FOREIGN KEY (`cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_receipt_file` FOREIGN KEY (`file_id`) REFERENCES `asso_file` (`file_id`),
  CONSTRAINT `fk_receipt_receipt_type` FOREIGN KEY (`rett_id`) REFERENCES `asso_receipt_type` (`rett_id`)
);
CREATE TABLE `asso_receipt_donation` (
  `rdo_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `rec_id` bigint(20) unsigned NOT NULL,
  `don_id` bigint(20) unsigned NOT NULL,
  `rdo_desc` varchar(80) DEFAULT NULL,
  `rdo_ts` timestamp NULL DEFAULT NULL,
  `rdo_mnt` decimal(15,6) DEFAULT NULL,
  `rdo_money` varchar(3) DEFAULT 'EUR',
  `ptyp_id` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`rdo_id`),
  KEY `fk_receipt_donation_receipt` (`rec_id`),
  KEY `fk_receipt_donation_donation` (`don_id`),
  KEY `fk_receipt_donation_broker` (`brk_id`),
  KEY `fk_receipt_donation_payment_type` (`ptyp_id`),
  CONSTRAINT `fk_receipt_donation_donation` FOREIGN KEY (`don_id`) REFERENCES `asso_donation` (`don_id`),
  CONSTRAINT `fk_receipt_donation_payment_type` FOREIGN KEY (`ptyp_id`) REFERENCES `asso_payment_type` (`ptyp_id`),
  CONSTRAINT `fk_receipt_donation_receipt` FOREIGN KEY (`rec_id`) REFERENCES `asso_receipt` (`rec_id`)
);
CREATE TABLE `crm_alert` (
  `alert_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `brk_id` bigint(20) unsigned NOT NULL,
  `site_id` bigint(20) unsigned DEFAULT NULL,
  `cau_id` bigint(20) unsigned DEFAULT NULL,
  `cli_id` bigint(20) unsigned DEFAULT NULL,
  `alert_from` timestamp NULL DEFAULT NULL,
  `alert_to` timestamp NULL DEFAULT NULL,
  `alert_ts` timestamp NULL DEFAULT NULL,
  `alert_text` text DEFAULT NULL,
  `alert_activ` tinyint(1) NOT NULL DEFAULT 1,
  `alert_priority` enum('IMPORTANT','CRITICAL','INFORMATION','NONE') NOT NULL DEFAULT 'NONE',
  PRIMARY KEY (`alert_id`),
  KEY `fk_alert_broker` (`brk_id`),
  KEY `fk_alert_cause` (`cau_id`),
  KEY `fk_alert_site` (`site_id`),
  KEY `fk_alert_client` (`cli_id`),
  CONSTRAINT `fk_alert_cause` FOREIGN KEY (`cau_id`) REFERENCES `asso_cause` (`cau_id`),
  CONSTRAINT `fk_alert_client` FOREIGN KEY (`cli_id`) REFERENCES `crm_client` (`cli_id`),
  CONSTRAINT `fk_alert_site` FOREIGN KEY (`site_id`) REFERENCES `asso_site` (`site_id`)
);